trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  PackageFeedEndpoint: 'https://pkgs.dev.azure.com/ramiMSFTDevOps/PsRepository/_packaging/PsRepositoryFeed/nuget/v2'

steps:
- powershell: |
    $pat = ConvertTo-SecureString ${env:pat_token} -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential("${env:userName}", $pat)
    Register-PSRepository -Name "PsRepositoryFeed" -SourceLocation "$(PackageFeedEndpoint)" -InstallationPolicy Trusted -Credential $credential
  displayName: 'Register PSRepository & Install module'
  env:
    pat_token: $patToken
    userName: $userName

- powershell: |
    #nuget install Get-Hello -Source "https://pkgs.dev.azure.com/ramiMSFTDevOps/PsRepository/_packaging/PsRepositoryFeed/nuget/v3/index.json"
    Install-Module -Name Get-Hello -Repository PsRepositoryFeed
  displayName: 'Install module'

